// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHYjJXde8-W1EOC70IjMuLuA6RSxUzkdU',
    appId: '1:496091312519:web:6de9c6df27d19609512322',
    messagingSenderId: '496091312519',
    projectId: 'lexi-learn-18adc',
    authDomain: 'lexi-learn-18adc.firebaseapp.com',
    storageBucket: 'lexi-learn-18adc.appspot.com',
    measurementId: 'G-CQECTR69W9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnXx-RTqk_AR237gGvag3fS2Gj5FpPu8E',
    appId: '1:496091312519:android:2f1b47468c0e7b87512322',
    messagingSenderId: '496091312519',
    projectId: 'lexi-learn-18adc',
    storageBucket: 'lexi-learn-18adc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjjp2vIcOoxgHzDH8mHUfK-0LCbavKu4w',
    appId: '1:496091312519:ios:dc321477b3bdeccc512322',
    messagingSenderId: '496091312519',
    projectId: 'lexi-learn-18adc',
    storageBucket: 'lexi-learn-18adc.appspot.com',
    iosBundleId: 'com.example.lexiLearn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjjp2vIcOoxgHzDH8mHUfK-0LCbavKu4w',
    appId: '1:496091312519:ios:bdc97d22da2ba477512322',
    messagingSenderId: '496091312519',
    projectId: 'lexi-learn-18adc',
    storageBucket: 'lexi-learn-18adc.appspot.com',
    iosBundleId: 'com.example.lexiLearn.RunnerTests',
  );
}
